//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.25 at 03:35:48 PM PYT 
//


package cl.vmetrix.xml.operation.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for equivalenteCreditoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="equivalenteCreditoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="creditoCorporativo" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="creditoNormativo" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="creditoFactor" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="creditoFactorInterno" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="creditoFactorNormativo" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "equivalenteCreditoType", propOrder = {
    "creditoCorporativo",
    "creditoNormativo",
    "creditoFactor",
    "creditoFactorInterno",
    "creditoFactorNormativo"
})
public class EquivalenteCreditoType {

    protected double creditoCorporativo;
    protected double creditoNormativo;
    protected double creditoFactor;
    protected double creditoFactorInterno;
    protected double creditoFactorNormativo;

    /**
     * Gets the value of the creditoCorporativo property.
     * 
     */
    public double getCreditoCorporativo() {
        return creditoCorporativo;
    }

    /**
     * Sets the value of the creditoCorporativo property.
     * 
     */
    public void setCreditoCorporativo(double value) {
        this.creditoCorporativo = value;
    }

    /**
     * Gets the value of the creditoNormativo property.
     * 
     */
    public double getCreditoNormativo() {
        return creditoNormativo;
    }

    /**
     * Sets the value of the creditoNormativo property.
     * 
     */
    public void setCreditoNormativo(double value) {
        this.creditoNormativo = value;
    }

    /**
     * Gets the value of the creditoFactor property.
     * 
     */
    public double getCreditoFactor() {
        return creditoFactor;
    }

    /**
     * Sets the value of the creditoFactor property.
     * 
     */
    public void setCreditoFactor(double value) {
        this.creditoFactor = value;
    }

    /**
     * Gets the value of the creditoFactorInterno property.
     * 
     */
    public double getCreditoFactorInterno() {
        return creditoFactorInterno;
    }

    /**
     * Sets the value of the creditoFactorInterno property.
     * 
     */
    public void setCreditoFactorInterno(double value) {
        this.creditoFactorInterno = value;
    }

    /**
     * Gets the value of the creditoFactorNormativo property.
     * 
     */
    public double getCreditoFactorNormativo() {
        return creditoFactorNormativo;
    }

    /**
     * Sets the value of the creditoFactorNormativo property.
     * 
     */
    public void setCreditoFactorNormativo(double value) {
        this.creditoFactorNormativo = value;
    }

}
