//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.24 at 02:29:08 PM PYT 
//


package cl.vmetrix.xml.operation.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for operationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="operationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="transaction" type="{}transactionType"/>
 *         &lt;element name="transactionInfo" type="{}transactionInfoType"/>
 *         &lt;element name="equivalenteCredito" type="{}equivalenteCreditoType"/>
 *         &lt;element name="profit" type="{}profitType"/>
 *         &lt;element name="side" type="{}sideType" maxOccurs="unbounded"/>
 *         &lt;element name="pricing" type="{}pricingType" maxOccurs="unbounded"/>
 *         &lt;element name="interest" type="{}interestType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="cashFlow" type="{}cashFlowType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="origin" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="dealNum" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="processDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "operationType", propOrder = {
    "transaction",
    "transactionInfo",
    "equivalenteCredito",
    "profit",
    "side",
    "pricing",
    "interest",
    "cashFlow"
})
@XmlRootElement(name="operation")
public class OperationType {

    @XmlElement(required = true)
    protected TransactionType transaction;
    @XmlElement(required = true)
    protected TransactionInfoType transactionInfo;
    @XmlElement(required = true)
    protected EquivalenteCreditoType equivalenteCredito;
    @XmlElement(required = true)
    protected ProfitType profit;
    @XmlElement(required = true)
    protected List<SideType> side;
    @XmlElement(required = true)
    protected List<PricingType> pricing;
    protected List<InterestType> interest;
    protected List<CashFlowType> cashFlow;
    @XmlAttribute(name = "origin")
    protected Integer origin;
    @XmlAttribute(name = "dealNum")
    protected Long dealNum;
    @XmlAttribute(name = "processDate")
    protected String processDate;

    /**
     * Gets the value of the transaction property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionType }
     *     
     */
    public TransactionType getTransaction() {
        return transaction;
    }

    /**
     * Sets the value of the transaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionType }
     *     
     */
    public void setTransaction(TransactionType value) {
        this.transaction = value;
    }

    /**
     * Gets the value of the transactionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionInfoType }
     *     
     */
    public TransactionInfoType getTransactionInfo() {
        return transactionInfo;
    }

    /**
     * Sets the value of the transactionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionInfoType }
     *     
     */
    public void setTransactionInfo(TransactionInfoType value) {
        this.transactionInfo = value;
    }

    /**
     * Gets the value of the equivalenteCredito property.
     * 
     * @return
     *     possible object is
     *     {@link EquivalenteCreditoType }
     *     
     */
    public EquivalenteCreditoType getEquivalenteCredito() {
        return equivalenteCredito;
    }

    /**
     * Sets the value of the equivalenteCredito property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquivalenteCreditoType }
     *     
     */
    public void setEquivalenteCredito(EquivalenteCreditoType value) {
        this.equivalenteCredito = value;
    }

    /**
     * Gets the value of the profit property.
     * 
     * @return
     *     possible object is
     *     {@link ProfitType }
     *     
     */
    public ProfitType getProfit() {
        return profit;
    }

    /**
     * Sets the value of the profit property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProfitType }
     *     
     */
    public void setProfit(ProfitType value) {
        this.profit = value;
    }

    /**
     * Gets the value of the side property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the side property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSide().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SideType }
     * 
     * 
     */
    public List<SideType> getSide() {
        if (side == null) {
            side = new ArrayList<SideType>();
        }
        return this.side;
    }

    /**
     * Gets the value of the pricing property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pricing property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPricing().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PricingType }
     * 
     * 
     */
    public List<PricingType> getPricing() {
        if (pricing == null) {
            pricing = new ArrayList<PricingType>();
        }
        return this.pricing;
    }

    /**
     * Gets the value of the interest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInterest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InterestType }
     * 
     * 
     */
    public List<InterestType> getInterest() {
        if (interest == null) {
            interest = new ArrayList<InterestType>();
        }
        return this.interest;
    }

    /**
     * Gets the value of the cashFlow property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cashFlow property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCashFlow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CashFlowType }
     * 
     * 
     */
    public List<CashFlowType> getCashFlow() {
        if (cashFlow == null) {
            cashFlow = new ArrayList<CashFlowType>();
        }
        return this.cashFlow;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOrigin(Integer value) {
        this.origin = value;
    }

    /**
     * Gets the value of the dealNum property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDealNum() {
        return dealNum;
    }

    /**
     * Sets the value of the dealNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDealNum(Long value) {
        this.dealNum = value;
    }

    /**
     * Gets the value of the processDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessDate() {
        return processDate;
    }

    /**
     * Sets the value of the processDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessDate(String value) {
        this.processDate = value;
    }

}
