//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.25 at 03:35:48 PM PYT 
//


package cl.vmetrix.xml.operation.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for profitType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="profitType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="currencyId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="ccy" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="mesaClientesCLP" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="mesaTradingClp" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="mesaClientesUsd" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="mesaTradingUsd" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="totalUsd" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="totalClp" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "profitType", propOrder = {
    "currencyId",
    "value",
    "ccy",
    "mesaClientesCLP",
    "mesaTradingClp",
    "mesaClientesUsd",
    "mesaTradingUsd",
    "totalUsd",
    "totalClp"
})
public class ProfitType {

    protected int currencyId;
    protected double value;
    protected int ccy;
    protected double mesaClientesCLP;
    protected double mesaTradingClp;
    protected double mesaClientesUsd;
    protected double mesaTradingUsd;
    protected double totalUsd;
    protected double totalClp;

    /**
     * Gets the value of the currencyId property.
     * 
     */
    public int getCurrencyId() {
        return currencyId;
    }

    /**
     * Sets the value of the currencyId property.
     * 
     */
    public void setCurrencyId(int value) {
        this.currencyId = value;
    }

    /**
     * Gets the value of the value property.
     * 
     */
    public double getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     */
    public void setValue(double value) {
        this.value = value;
    }

    /**
     * Gets the value of the ccy property.
     * 
     */
    public int getCcy() {
        return ccy;
    }

    /**
     * Sets the value of the ccy property.
     * 
     */
    public void setCcy(int value) {
        this.ccy = value;
    }

    /**
     * Gets the value of the mesaClientesCLP property.
     * 
     */
    public double getMesaClientesCLP() {
        return mesaClientesCLP;
    }

    /**
     * Sets the value of the mesaClientesCLP property.
     * 
     */
    public void setMesaClientesCLP(double value) {
        this.mesaClientesCLP = value;
    }

    /**
     * Gets the value of the mesaTradingClp property.
     * 
     */
    public double getMesaTradingClp() {
        return mesaTradingClp;
    }

    /**
     * Sets the value of the mesaTradingClp property.
     * 
     */
    public void setMesaTradingClp(double value) {
        this.mesaTradingClp = value;
    }

    /**
     * Gets the value of the mesaClientesUsd property.
     * 
     */
    public double getMesaClientesUsd() {
        return mesaClientesUsd;
    }

    /**
     * Sets the value of the mesaClientesUsd property.
     * 
     */
    public void setMesaClientesUsd(double value) {
        this.mesaClientesUsd = value;
    }

    /**
     * Gets the value of the mesaTradingUsd property.
     * 
     */
    public double getMesaTradingUsd() {
        return mesaTradingUsd;
    }

    /**
     * Sets the value of the mesaTradingUsd property.
     * 
     */
    public void setMesaTradingUsd(double value) {
        this.mesaTradingUsd = value;
    }

    /**
     * Gets the value of the totalUsd property.
     * 
     */
    public double getTotalUsd() {
        return totalUsd;
    }

    /**
     * Sets the value of the totalUsd property.
     * 
     */
    public void setTotalUsd(double value) {
        this.totalUsd = value;
    }

    /**
     * Gets the value of the totalClp property.
     * 
     */
    public double getTotalClp() {
        return totalClp;
    }

    /**
     * Sets the value of the totalClp property.
     * 
     */
    public void setTotalClp(double value) {
        this.totalClp = value;
    }

}
