/*******************************************************************************
 * Copyright (c) 2016 VMetrix SPA.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.25 at 03:35:48 PM PYT 
//


package cl.vmetrix.operation.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cashFlowType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cashFlowType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sideId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="accountingDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fixingDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="npv" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="fixingRate" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="df" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *       &lt;attribute name="cashFlowId" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="cashFlowTypeId" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cashFlowType", propOrder = {
    "sideId",
    "startDate",
    "endDate",
    "accountingDate",
    "fixingDate",
    "amount",
    "npv",
    "fixingRate",
    "df"
})
public class CashFlowType {

    protected int sideId;
    @XmlElement(required = true)
    protected String startDate;
    @XmlElement(required = true)
    protected String endDate;
    @XmlElement(required = true)
    protected String accountingDate;
    @XmlElement(required = true)
    protected String fixingDate;
    protected double amount;
    protected double npv;
    protected double fixingRate;
    protected double df;
    @XmlAttribute(name = "cashFlowId")
    protected Integer cashFlowId;
    @XmlAttribute(name = "cashFlowTypeId")
    protected Integer cashFlowTypeId;

    /**
     * Gets the value of the sideId property.
     * 
     */
    public int getSideId() {
        return sideId;
    }

    /**
     * Sets the value of the sideId property.
     * 
     */
    public void setSideId(int value) {
        this.sideId = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartDate(String value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndDate(String value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the accountingDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountingDate() {
        return accountingDate;
    }

    /**
     * Sets the value of the accountingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountingDate(String value) {
        this.accountingDate = value;
    }

    /**
     * Gets the value of the fixingDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFixingDate() {
        return fixingDate;
    }

    /**
     * Sets the value of the fixingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFixingDate(String value) {
        this.fixingDate = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     */
    public double getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     */
    public void setAmount(double value) {
        this.amount = value;
    }

    /**
     * Gets the value of the npv property.
     * 
     */
    public double getNpv() {
        return npv;
    }

    /**
     * Sets the value of the npv property.
     * 
     */
    public void setNpv(double value) {
        this.npv = value;
    }

    /**
     * Gets the value of the fixingRate property.
     * 
     */
    public double getFixingRate() {
        return fixingRate;
    }

    /**
     * Sets the value of the fixingRate property.
     * 
     */
    public void setFixingRate(double value) {
        this.fixingRate = value;
    }

    /**
     * Gets the value of the df property.
     * 
     */
    public double getDf() {
        return df;
    }

    /**
     * Sets the value of the df property.
     * 
     */
    public void setDf(double value) {
        this.df = value;
    }

    /**
     * Gets the value of the cashFlowId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCashFlowId() {
        return cashFlowId;
    }

    /**
     * Sets the value of the cashFlowId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCashFlowId(Integer value) {
        this.cashFlowId = value;
    }

    /**
     * Gets the value of the cashFlowTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCashFlowTypeId() {
        return cashFlowTypeId;
    }

    /**
     * Sets the value of the cashFlowTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCashFlowTypeId(Integer value) {
        this.cashFlowTypeId = value;
    }

}
