/*******************************************************************************
 * Copyright (c) 2016 VMetrix SPA.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.25 at 03:35:48 PM PYT 
//


package cl.vmetrix.operation.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pricingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pricingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sideId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="mtm" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="mtmCcy" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="baseMtm" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="baseMtmUsd" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="delta" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="gamma" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="vega" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="beta" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="rhoLocal" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="rhoForanea" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="theta" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="volga" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="pnl" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="unrealizedPnl" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="pnlFxUnrealized" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="currentCash" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="baseUnrealizedPnl" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pricingType", propOrder = {
    "sideId",
    "mtm",
    "mtmCcy",
    "baseMtm",
    "baseMtmUsd",
    "delta",
    "gamma",
    "vega",
    "beta",
    "rhoLocal",
    "rhoForanea",
    "theta",
    "volga",
    "pnl",
    "unrealizedPnl",
    "pnlFxUnrealized",
    "currentCash",
    "baseUnrealizedPnl"
})
public class PricingType {

    protected int sideId;
    protected double mtm;
    protected double mtmCcy;
    protected double baseMtm;
    protected double baseMtmUsd;
    protected double delta;
    protected double gamma;
    protected double vega;
    protected double beta;
    protected double rhoLocal;
    protected double rhoForanea;
    protected double theta;
    protected double volga;
    protected double pnl;
    protected double unrealizedPnl;
    protected double pnlFxUnrealized;
    protected double currentCash;
    protected double baseUnrealizedPnl;

    /**
     * Gets the value of the sideId property.
     * 
     */
    public int getSideId() {
        return sideId;
    }

    /**
     * Sets the value of the sideId property.
     * 
     */
    public void setSideId(int value) {
        this.sideId = value;
    }

    /**
     * Gets the value of the mtm property.
     * 
     */
    public double getMtm() {
        return mtm;
    }

    /**
     * Sets the value of the mtm property.
     * 
     */
    public void setMtm(double value) {
        this.mtm = value;
    }

    /**
     * Gets the value of the mtmCcy property.
     * 
     */
    public double getMtmCcy() {
        return mtmCcy;
    }

    /**
     * Sets the value of the mtmCcy property.
     * 
     */
    public void setMtmCcy(double value) {
        this.mtmCcy = value;
    }

    /**
     * Gets the value of the baseMtm property.
     * 
     */
    public double getBaseMtm() {
        return baseMtm;
    }

    /**
     * Sets the value of the baseMtm property.
     * 
     */
    public void setBaseMtm(double value) {
        this.baseMtm = value;
    }

    /**
     * Gets the value of the baseMtmUsd property.
     * 
     */
    public double getBaseMtmUsd() {
        return baseMtmUsd;
    }

    /**
     * Sets the value of the baseMtmUsd property.
     * 
     */
    public void setBaseMtmUsd(double value) {
        this.baseMtmUsd = value;
    }

    /**
     * Gets the value of the delta property.
     * 
     */
    public double getDelta() {
        return delta;
    }

    /**
     * Sets the value of the delta property.
     * 
     */
    public void setDelta(double value) {
        this.delta = value;
    }

    /**
     * Gets the value of the gamma property.
     * 
     */
    public double getGamma() {
        return gamma;
    }

    /**
     * Sets the value of the gamma property.
     * 
     */
    public void setGamma(double value) {
        this.gamma = value;
    }

    /**
     * Gets the value of the vega property.
     * 
     */
    public double getVega() {
        return vega;
    }

    /**
     * Sets the value of the vega property.
     * 
     */
    public void setVega(double value) {
        this.vega = value;
    }

    /**
     * Gets the value of the beta property.
     * 
     */
    public double getBeta() {
        return beta;
    }

    /**
     * Sets the value of the beta property.
     * 
     */
    public void setBeta(double value) {
        this.beta = value;
    }

    /**
     * Gets the value of the rhoLocal property.
     * 
     */
    public double getRhoLocal() {
        return rhoLocal;
    }

    /**
     * Sets the value of the rhoLocal property.
     * 
     */
    public void setRhoLocal(double value) {
        this.rhoLocal = value;
    }

    /**
     * Gets the value of the rhoForanea property.
     * 
     */
    public double getRhoForanea() {
        return rhoForanea;
    }

    /**
     * Sets the value of the rhoForanea property.
     * 
     */
    public void setRhoForanea(double value) {
        this.rhoForanea = value;
    }

    /**
     * Gets the value of the theta property.
     * 
     */
    public double getTheta() {
        return theta;
    }

    /**
     * Sets the value of the theta property.
     * 
     */
    public void setTheta(double value) {
        this.theta = value;
    }

    /**
     * Gets the value of the volga property.
     * 
     */
    public double getVolga() {
        return volga;
    }

    /**
     * Sets the value of the volga property.
     * 
     */
    public void setVolga(double value) {
        this.volga = value;
    }

    /**
     * Gets the value of the pnl property.
     * 
     */
    public double getPnl() {
        return pnl;
    }

    /**
     * Sets the value of the pnl property.
     * 
     */
    public void setPnl(double value) {
        this.pnl = value;
    }

    /**
     * Gets the value of the unrealizedPnl property.
     * 
     */
    public double getUnrealizedPnl() {
        return unrealizedPnl;
    }

    /**
     * Sets the value of the unrealizedPnl property.
     * 
     */
    public void setUnrealizedPnl(double value) {
        this.unrealizedPnl = value;
    }

    /**
     * Gets the value of the pnlFxUnrealized property.
     * 
     */
    public double getPnlFxUnrealized() {
        return pnlFxUnrealized;
    }

    /**
     * Sets the value of the pnlFxUnrealized property.
     * 
     */
    public void setPnlFxUnrealized(double value) {
        this.pnlFxUnrealized = value;
    }

    /**
     * Gets the value of the currentCash property.
     * 
     */
    public double getCurrentCash() {
        return currentCash;
    }

    /**
     * Sets the value of the currentCash property.
     * 
     */
    public void setCurrentCash(double value) {
        this.currentCash = value;
    }

    /**
     * Gets the value of the baseUnrealizedPnl property.
     * 
     */
    public double getBaseUnrealizedPnl() {
        return baseUnrealizedPnl;
    }

    /**
     * Sets the value of the baseUnrealizedPnl property.
     * 
     */
    public void setBaseUnrealizedPnl(double value) {
        this.baseUnrealizedPnl = value;
    }

}
