/*******************************************************************************
 * Copyright (c) 2016 VMetrix SPA.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.25 at 03:35:48 PM PYT 
//

package cl.vmetrix.operation.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for transactionType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="transactionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="instrumentId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="portFolio" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="partyId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="facilityId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="tradeDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="et" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="modalidadPago" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nemo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="serie" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tirCompra" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="tirMercado" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="strike" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="partySecuencia" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="paymentConvId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="statusId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="groupId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="callPutId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="offsetTranType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="traderName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="traderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="etNp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "transactionType", propOrder = { "instrumentId", "portFolio",
		"partyId", "facilityId", "tradeDate", "startDate", "endDate", "et",
		"modalidadPago", "nemo", "serie", "tirCompra", "tirMercado", "strike",
		"partySecuencia", "paymentConvId", "statusId", "groupId", "callPutId",
		"offsetTranType", "traderName", "traderId", "etNp" })
public class TransactionType {

	protected int instrumentId;
	protected int portFolio;
	protected int partyId;
	protected int facilityId;
	@XmlElement(required = true)
	protected String tradeDate;
	@XmlElement(required = true)
	protected String startDate;
	@XmlElement(required = true)
	protected String endDate;
	@XmlElement(required = true)
	protected String et;
	@XmlElement(required = true)
	protected String modalidadPago;
	@XmlElement(required = true)
	protected String nemo;
	@XmlElement(required = true)
	protected String serie;
	protected double tirCompra;
	protected double tirMercado;
	protected double strike;
	protected int partySecuencia;
	protected int paymentConvId;
	protected int statusId;
	protected int groupId;
	protected int callPutId;
	@XmlElement(required = true)
	protected String offsetTranType;
	@XmlElement(required = true)
	protected String traderName;
	@XmlElement(required = true)
	protected String traderId;
	@XmlElement(required = true)
	protected String etNp;

	/**
	 * Gets the value of the instrumentId property.
	 * 
	 */
	public int getInstrumentId() {
		return instrumentId;
	}

	/**
	 * Sets the value of the instrumentId property.
	 * 
	 */
	public void setInstrumentId(int value) {
		this.instrumentId = value;
	}

	/**
	 * Gets the value of the portFolio property.
	 * 
	 */
	public int getPortFolio() {
		return portFolio;
	}

	/**
	 * Sets the value of the portFolio property.
	 * 
	 */
	public void setPortFolio(int value) {
		this.portFolio = value;
	}

	/**
	 * Gets the value of the partyId property.
	 * 
	 */
	public int getPartyId() {
		return partyId;
	}

	/**
	 * Sets the value of the partyId property.
	 * 
	 */
	public void setPartyId(int value) {
		this.partyId = value;
	}

	/**
	 * Gets the value of the facilityId property.
	 * 
	 */
	public int getFacilityId() {
		return facilityId;
	}

	/**
	 * Sets the value of the facilityId property.
	 * 
	 */
	public void setFacilityId(int value) {
		this.facilityId = value;
	}

	/**
	 * Gets the value of the tradeDate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTradeDate() {
		return tradeDate;
	}

	/**
	 * Sets the value of the tradeDate property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTradeDate(String value) {
		this.tradeDate = value;
	}

	/**
	 * Gets the value of the startDate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStartDate() {
		return startDate;
	}

	/**
	 * Sets the value of the startDate property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStartDate(String value) {
		this.startDate = value;
	}

	/**
	 * Gets the value of the endDate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEndDate() {
		return endDate;
	}

	/**
	 * Sets the value of the endDate property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEndDate(String value) {
		this.endDate = value;
	}

	/**
	 * Gets the value of the et property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEt() {
		return et;
	}

	/**
	 * Sets the value of the et property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEt(String value) {
		this.et = value;
	}

	/**
	 * Gets the value of the modalidadPago property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getModalidadPago() {
		return modalidadPago;
	}

	/**
	 * Sets the value of the modalidadPago property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setModalidadPago(String value) {
		this.modalidadPago = value;
	}

	/**
	 * Gets the value of the nemo property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNemo() {
		return nemo;
	}

	/**
	 * Sets the value of the nemo property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNemo(String value) {
		this.nemo = value;
	}

	/**
	 * Gets the value of the serie property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSerie() {
		return serie;
	}

	/**
	 * Sets the value of the serie property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSerie(String value) {
		this.serie = value;
	}

	/**
	 * Gets the value of the tirCompra property.
	 * 
	 */
	public double getTirCompra() {
		return tirCompra;
	}

	/**
	 * Sets the value of the tirCompra property.
	 * 
	 */
	public void setTirCompra(double value) {
		this.tirCompra = value;
	}

	/**
	 * Gets the value of the tirMercado property.
	 * 
	 */
	public double getTirMercado() {
		return tirMercado;
	}

	/**
	 * Sets the value of the tirMercado property.
	 * 
	 */
	public void setTirMercado(double value) {
		this.tirMercado = value;
	}

	/**
	 * Gets the value of the strike property.
	 * 
	 */
	public double getStrike() {
		return strike;
	}

	/**
	 * Sets the value of the strike property.
	 * 
	 */
	public void setStrike(double value) {
		this.strike = value;
	}

	/**
	 * Gets the value of the partySecuencia property.
	 * 
	 */
	public int getPartySecuencia() {
		return partySecuencia;
	}

	/**
	 * Sets the value of the partySecuencia property.
	 * 
	 */
	public void setPartySecuencia(int value) {
		this.partySecuencia = value;
	}

	/**
	 * Gets the value of the paymentConvId property.
	 * 
	 */
	public int getPaymentConvId() {
		return paymentConvId;
	}

	/**
	 * Sets the value of the paymentConvId property.
	 * 
	 */
	public void setPaymentConvId(int value) {
		this.paymentConvId = value;
	}

	/**
	 * Gets the value of the statusId property.
	 * 
	 */
	public int getStatusId() {
		return statusId;
	}

	/**
	 * Sets the value of the statusId property.
	 * 
	 */
	public void setStatusId(int value) {
		this.statusId = value;
	}

	/**
	 * Gets the value of the groupId property.
	 * 
	 */
	public int getGroupId() {
		return groupId;
	}

	/**
	 * Sets the value of the groupId property.
	 * 
	 */
	public void setGroupId(int value) {
		this.groupId = value;
	}

	/**
	 * Gets the value of the callPutId property.
	 * 
	 */
	public int getCallPutId() {
		return callPutId;
	}

	/**
	 * Sets the value of the callPutId property.
	 * 
	 */
	public void setCallPutId(int value) {
		this.callPutId = value;
	}

	/**
	 * Gets the value of the offsetTranType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOffsetTranType() {
		return offsetTranType;
	}

	/**
	 * Sets the value of the offsetTranType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOffsetTranType(String value) {
		this.offsetTranType = value;
	}

	/**
	 * Gets the value of the traderName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTraderName() {
		return traderName;
	}

	/**
	 * Sets the value of the traderName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTraderName(String value) {
		this.traderName = value;
	}

	/**
	 * Gets the value of the traderId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTraderId() {
		return traderId;
	}

	/**
	 * Sets the value of the traderId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTraderId(String value) {
		this.traderId = value;
	}

	/**
	 * Gets the value of the etNp property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEtNp() {
		return etNp;
	}

	/**
	 * Sets the value of the etNp property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEtNp(String value) {
		this.etNp = value;
	}

}
